const qs=[
["Hamstrings","Give me five exercises that train the hamstrings, and tell me why you might choose each one."],
["Coaching","Teach a brand-new client how to perform a goblet squat in under 45 seconds."],
["Modification","Your client feels an RDL mostly in the lower back. What do you check and change?"],
["Programming","Build a 30-minute full-body session for a healthy 55-year-old beginner."],
["Safety","A client reports sharp knee pain during a lunge. What do you do next?"],
["Anatomy","Explain the difference between a leg curl and an RDL in terms of hamstring function."],
["Curveball","The cable station is occupied. Give me two substitutions for a seated cable row and defend them."],
["Client","A 70-year-old beginner has poor balance. Choose three leg exercises and explain your choices."]
];
const ex=[
{name:"Goblet Squat",group:"Squat • Quads + Glutes",cue:"Weight close. Brace. Sit between the hips. Knees track with toes. Push the floor away.",reg:"Box squat / sit-to-stand",prog:"Heavier goblet or front squat",why:"Easy to teach, load and observe."},
{name:"DB Romanian Deadlift",group:"Hinge • Hamstrings + Glutes",cue:"Soft knees. Hips back. Dumbbells close. Stop before spinal position changes.",reg:"Wall hinge / elevated KB deadlift",prog:"Barbell or single-leg RDL",why:"Teaches hip hinge and posterior-chain loading."},
{name:"Reverse Lunge",group:"Lunge • Quads + Glutes",cue:"Step back under control. Stay tall. Front foot planted. Push the floor away.",reg:"Supported split squat",prog:"Loaded or walking lunge",why:"Unilateral strength with manageable deceleration demands."},
{name:"Seated Leg Curl",group:"Knee Flexion • Hamstrings",cue:"Align knee with machine pivot. Control both directions. Avoid lifting hips.",reg:"Lighter load / shorter ROM",prog:"Single-leg curl",why:"Stable way to isolate knee-flexion function."},
{name:"Glute Bridge",group:"Hip Extension • Glutes",cue:"Ribs down. Brace. Drive through feet. Extend hips without over-arching.",reg:"Shorter ROM",prog:"Hip thrust / loaded bridge",why:"Accessible glute-focused hip extension."},
{name:"Lat Pulldown",group:"Vertical Pull • Lats + Biceps",cue:"Stay tall. Set shoulders. Drive elbows toward sides. Control return.",reg:"Band pulldown",prog:"Assisted pull-up / pull-up",why:"Scalable vertical pulling pattern."},
{name:"Incline Push-up",group:"Horizontal Push • Chest + Triceps",cue:"Straight body line. Brace. Lower chest between hands. Push away.",reg:"Wall push-up",prog:"Floor push-up / DB press",why:"Easy to scale by changing hand height."},
{name:"Seated Cable Row",group:"Horizontal Pull • Back + Biceps",cue:"Stay tall. Ribs controlled. Drive elbows back. Finish without shrugging.",reg:"Band row",prog:"Single-arm or unsupported row",why:"Stable horizontal pull with easy load adjustment."}
];
let idx=0;
function show(id){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelector('[data-view="'+id+'"]').classList.add("active")}
function renderExercises(){document.getElementById("exerciseList").innerHTML=ex.map(e=>'<div class="exercise"><h3>'+e.name+'</h3><span class="badge">'+e.group+'</span><p><b>Coach it:</b> '+e.cue+'</p><p><b>Regression:</b> '+e.reg+' &nbsp; <b>Progression:</b> '+e.prog+'</p><p class="muted"><b>Why prescribe it?</b> '+e.why+'</p></div>').join("")}
function nextQ(){idx=Math.floor(Math.random()*qs.length);document.getElementById("qcat").textContent=qs[idx][0];document.getElementById("question").textContent=qs[idx][1];document.getElementById("response").value="";document.getElementById("feedback").innerHTML=""}
function selfScore(n){let d=JSON.parse(localStorage.getItem("fitcoach")||'{"attempts":0,"total":0}');d.attempts++;d.total+=n;localStorage.setItem("fitcoach",JSON.stringify(d));document.getElementById("feedback").innerHTML='<p><b>Saved.</b> Now say one thing you would improve before the real interview.</p>';stats()}
function stats(){let d=JSON.parse(localStorage.getItem("fitcoach")||'{"attempts":0,"total":0}');let pct=d.attempts?Math.round(d.total/d.attempts*20):0;document.querySelectorAll(".attempts").forEach(x=>x.textContent=d.attempts);document.querySelectorAll(".readiness").forEach(x=>x.textContent=pct+"%");document.querySelectorAll(".fill").forEach(x=>x.style.width=pct+"%")}
document.addEventListener("DOMContentLoaded",()=>{renderExercises();nextQ();stats()});
function clientData(){return JSON.parse(localStorage.getItem("fitcoach_clients")||"[]")}
function saveClients(d){localStorage.setItem("fitcoach_clients",JSON.stringify(d));renderClients()}
function addClient(){const n=document.getElementById("clientName").value.trim();if(!n)return alert("Add a client name.");const d=clientData();d.push({id:Date.now(),name:n,goal:document.getElementById("clientGoal").value.trim(),notes:document.getElementById("clientNotes").value.trim(),sessions:[]});saveClients(d);document.getElementById("clientName").value="";document.getElementById("clientGoal").value="";document.getElementById("clientNotes").value=""}
function addSession(id){const d=clientData(),c=d.find(x=>x.id===id);if(!c)return;const date=prompt("Session date (YYYY-MM-DD)",new Date().toISOString().slice(0,10));if(!date)return;const exercises=prompt("Exercises performed (include sets/reps/load as useful)","");const response=prompt("How did the client fare? Energy, form, difficulty, wins?","");const issues=prompt("Any pain, discomfort, limitations, or other issues?","");const next=prompt("Plan or adjustments for next session","");c.sessions.unshift({date,exercises,response,issues,next});saveClients(d)}
function deleteClient(id){if(!confirm("Delete this client and session history?"))return;saveClients(clientData().filter(x=>x.id!==id))}
function renderClients(){const el=document.getElementById("clientList");if(!el)return;const d=clientData();if(!d.length){el.innerHTML='<p class="muted">No clients yet. Add the first client above.</p>';return}el.innerHTML=d.map(c=>'<div class="client-card"><div class="client-head"><div><h3>'+esc(c.name)+'</h3><span class="badge">'+esc(c.goal||"Goal not entered")+'</span></div><div><button onclick="addSession('+c.id+')">+ Log Session</button> <button class="secondary" onclick="deleteClient('+c.id+')">Delete</button></div></div><p>'+esc(c.notes||"No background notes yet.")+'</p><h4>Session History ('+c.sessions.length+')</h4>'+(c.sessions.length?c.sessions.map(s=>'<div class="session"><b>'+esc(s.date)+'</b><p><b>Exercises:</b> '+esc(s.exercises||"—")+'</p><p><b>Client response:</b> '+esc(s.response||"—")+'</p><p><b>Issues:</b> '+esc(s.issues||"None recorded")+'</p><p><b>Next session:</b> '+esc(s.next||"—")+'</p></div>').join(""):'<p class="muted">No sessions logged yet.</p>')+'</div>').join("")}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
document.addEventListener("DOMContentLoaded",renderClients);

const GOOGLE_REVIEW_URL="";
function feedbackData(){return JSON.parse(localStorage.getItem("fitcoach_feedback")||"[]")}
function saveFeedback(d){localStorage.setItem("fitcoach_feedback",JSON.stringify(d));renderFeedback()}
function submitFeedback(){const text=document.getElementById("feedbackText").value.trim();if(!text)return alert("Please add your feedback first.");const d=feedbackData();d.unshift({id:Date.now(),name:document.getElementById("feedbackName").value.trim()||"Anonymous client",text,consent:document.getElementById("feedbackConsent").checked,date:new Date().toLocaleDateString()});saveFeedback(d);document.getElementById("feedbackName").value="";document.getElementById("feedbackText").value="";document.getElementById("feedbackConsent").checked=false;document.getElementById("feedbackThanks").innerHTML="<b>Thank you.</b> Your feedback was saved for Elise."}
function openGoogleReview(){if(!GOOGLE_REVIEW_URL)return alert("Elise’s Google review link is not connected yet.");window.open(GOOGLE_REVIEW_URL,"_blank","noopener")}
function renderFeedback(){const el=document.getElementById("feedbackList");if(!el)return;const d=feedbackData();el.innerHTML=d.length?d.map(f=>'<div class="session"><div class="client-head"><b>'+esc(f.name)+'</b><span class="badge">'+(f.consent?"TESTIMONIAL OK":"PRIVATE FEEDBACK")+'</span></div><p>“'+esc(f.text)+'”</p><p class="muted">'+esc(f.date)+'</p></div>').join(""):'<p class="muted">No client feedback yet.</p>';const b=document.getElementById("googleReviewBtn");if(b&&!GOOGLE_REVIEW_URL){b.disabled=true;b.title="Connect Elise’s Google Business Profile review link first."}}
document.addEventListener("DOMContentLoaded",renderFeedback);

const portalViews={
workout:'<div class="grid"><div class="card wide"><p class="muted">NEXT WORKOUT</p><h2>Full Body Strength • Session 13</h2><p>Built for your current goals. Tap each movement as you complete it.</p><div class="workout-checks"><label><input type="checkbox"> Goblet Squat <b>3 × 10</b></label><label><input type="checkbox"> DB Romanian Deadlift <b>3 × 10</b></label><label><input type="checkbox"> Incline Push-up <b>3 × 8</b></label><label><input type="checkbox"> Seated Cable Row <b>3 × 12</b></label></div></div><div class="card"><p class="muted">FROM ELISE</p><h3>Today’s focus</h3><p>Move with control. Own the hinge position and leave two strong reps in reserve.</p></div></div>',
recap:'<div class="grid"><div class="card wide"><p class="muted">LAST SESSION</p><h2>Strong work.</h2><p><b>Wins:</b> Better squat depth and steadier tempo. RDL position improved after the second set.</p><p><b>Next time:</b> Add a small load increase if warm-up reps feel crisp.</p></div><div class="card"><h3>How did it feel?</h3><div class="feel-row"><button onclick="portalFeel(this)">Easy</button><button onclick="portalFeel(this)">Just Right</button><button onclick="portalFeel(this)">Tough</button></div><textarea class="answer" placeholder="Anything Elise should know before the next session?"></textarea></div></div>',
progress:'<div class="grid"><div class="card wide"><p class="muted">PROGRESS</p><h2>Momentum you can see.</h2><div class="progress-bars"><p>Workout consistency <span>80%</span></p><div class="bar"><div class="fill" style="width:80%"></div></div><p>Strength goal <span>68%</span></p><div class="bar"><div class="fill" style="width:68%"></div></div><p>Movement confidence <span>75%</span></p><div class="bar"><div class="fill" style="width:75%"></div></div></div></div><div class="card"><h3>Recent wins</h3><p>✓ 4 sessions this month</p><p>✓ New goblet squat best</p><p>✓ Improved hinge control</p></div></div>',
videos:'<div class="grid"><div class="card wide"><p class="muted">COACH VIDEO LIBRARY</p><h2>Your form cues, saved.</h2><p>Short clips Elise records during training will live here with her coaching note and the session date.</p><div class="video-placeholder"><b>FORM CHECK</b><span>RDL • Keep the weights close and finish tall.</span></div></div><div class="card"><h3>Video privacy</h3><p>Client training clips will be private to Elise and that client once secure media storage and login are connected.</p></div></div>',
message:'<div class="grid"><div class="card wide"><p class="muted">CHECK IN</p><h2>Message Elise</h2><textarea id="portalMessage" class="answer" placeholder="Question, win, soreness, schedule note, or anything Elise should know..."></textarea><button onclick="portalMessage()">Send Check-in</button><p id="portalMessageStatus"></p></div><div class="card"><h3>Quick check-in</h3><p>Use this between sessions so Elise can adjust the next workout with context.</p></div></div>'
};
function portalTab(name){document.querySelectorAll("[data-portal]").forEach(b=>b.classList.toggle("active",b.dataset.portal===name));const el=document.getElementById("portalContent");if(el)el.innerHTML=portalViews[name]||portalViews.workout}
function portalFeel(btn){btn.parentElement.querySelectorAll("button").forEach(b=>b.classList.remove("selected"));btn.classList.add("selected")}
function portalMessage(){const v=document.getElementById("portalMessage").value.trim();document.getElementById("portalMessageStatus").innerHTML=v?"<b>Check-in saved.</b> This demo will sync to Elise once secure client accounts are connected.":"Add a message first."}
document.addEventListener("DOMContentLoaded",()=>portalTab("workout"));
