const qs=[
["Hamstrings","Give me five exercises that train the hamstrings, and tell me why you might choose each one."],
["Coaching","Teach a brand-new client how to perform a goblet squat in under 45 seconds."],
["Modification","Your client feels an RDL mostly in the lower back. What do you check and change?"],
["Programming","Build a 30-minute full-body session for a healthy 55-year-old beginner."],
["Safety","A client reports sharp knee pain during a lunge. What do you do next?"],
["Anatomy","Explain the difference between a leg curl and an RDL in terms of hamstring function."],
["Curveball","The cable station is occupied. Give me two substitutions for a seated cable row and defend them."],
["Client","A 70-year-old beginner has poor balance. Choose three leg exercises and explain your choices."]
];
const ex=[
{name:"Goblet Squat",group:"Squat • Quads + Glutes",cue:"Weight close. Brace. Sit between the hips. Knees track with toes. Push the floor away.",reg:"Box squat / sit-to-stand",prog:"Heavier goblet or front squat",why:"Easy to teach, load and observe."},
{name:"DB Romanian Deadlift",group:"Hinge • Hamstrings + Glutes",cue:"Soft knees. Hips back. Dumbbells close. Stop before spinal position changes.",reg:"Wall hinge / elevated KB deadlift",prog:"Barbell or single-leg RDL",why:"Teaches hip hinge and posterior-chain loading."},
{name:"Reverse Lunge",group:"Lunge • Quads + Glutes",cue:"Step back under control. Stay tall. Front foot planted. Push the floor away.",reg:"Supported split squat",prog:"Loaded or walking lunge",why:"Unilateral strength with manageable deceleration demands."},
{name:"Seated Leg Curl",group:"Knee Flexion • Hamstrings",cue:"Align knee with machine pivot. Control both directions. Avoid lifting hips.",reg:"Lighter load / shorter ROM",prog:"Single-leg curl",why:"Stable way to isolate knee-flexion function."},
{name:"Glute Bridge",group:"Hip Extension • Glutes",cue:"Ribs down. Brace. Drive through feet. Extend hips without over-arching.",reg:"Shorter ROM",prog:"Hip thrust / loaded bridge",why:"Accessible glute-focused hip extension."},
{name:"Lat Pulldown",group:"Vertical Pull • Lats + Biceps",cue:"Stay tall. Set shoulders. Drive elbows toward sides. Control return.",reg:"Band pulldown",prog:"Assisted pull-up / pull-up",why:"Scalable vertical pulling pattern."},
{name:"Incline Push-up",group:"Horizontal Push • Chest + Triceps",cue:"Straight body line. Brace. Lower chest between hands. Push away.",reg:"Wall push-up",prog:"Floor push-up / DB press",why:"Easy to scale by changing hand height."},
{name:"Seated Cable Row",group:"Horizontal Pull • Back + Biceps",cue:"Stay tall. Ribs controlled. Drive elbows back. Finish without shrugging.",reg:"Band row",prog:"Single-arm or unsupported row",why:"Stable horizontal pull with easy load adjustment."}
];
let idx=0;
function show(id){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");const tab=document.querySelector('[data-view="'+id+'"]');if(tab)tab.classList.add("active");if(id==="clients"){renderClients();refreshDatabaseSessionClientPicker()}}
function renderExercises(){document.getElementById("exerciseList").innerHTML=ex.map(e=>'<div class="exercise"><h3>'+e.name+'</h3><span class="badge">'+e.group+'</span><p><b>Coach it:</b> '+e.cue+'</p><p><b>Regression:</b> '+e.reg+' &nbsp; <b>Progression:</b> '+e.prog+'</p><p class="muted"><b>Why prescribe it?</b> '+e.why+'</p></div>').join("")}
function nextQ(){idx=Math.floor(Math.random()*qs.length);document.getElementById("qcat").textContent=qs[idx][0];document.getElementById("question").textContent=qs[idx][1];document.getElementById("response").value="";document.getElementById("feedback").innerHTML=""}
function selfScore(n){let d=JSON.parse(localStorage.getItem("fitcoach")||'{"attempts":0,"total":0}');d.attempts++;d.total+=n;localStorage.setItem("fitcoach",JSON.stringify(d));document.getElementById("feedback").innerHTML='<p><b>Saved.</b> Now say one thing you would improve before the real interview.</p>';stats()}
function stats(){let d=JSON.parse(localStorage.getItem("fitcoach")||'{"attempts":0,"total":0}');let pct=d.attempts?Math.round(d.total/d.attempts*20):0;document.querySelectorAll(".attempts").forEach(x=>x.textContent=d.attempts);document.querySelectorAll(".readiness").forEach(x=>x.textContent=pct+"%");document.querySelectorAll(".fill").forEach(x=>x.style.width=pct+"%")}
document.addEventListener("DOMContentLoaded",()=>{renderExercises();nextQ();stats()});
function clientData(){return JSON.parse(localStorage.getItem("fitcoach_clients")||"[]")}
function saveClients(d){localStorage.setItem("fitcoach_clients",JSON.stringify(d));renderClients();refreshSessionClientPicker()}
function addClient(){const n=document.getElementById("clientName").value.trim();if(!n)return alert("Add a client name.");const d=clientData();d.push({id:Date.now(),name:n,goal:document.getElementById("clientGoal").value.trim(),notes:document.getElementById("clientNotes").value.trim(),sessions:[]});saveClients(d);document.getElementById("clientName").value="";document.getElementById("clientGoal").value="";document.getElementById("clientNotes").value=""}
function refreshSessionClientPicker(selectedId){const s=document.getElementById("sessionClientPicker");if(!s)return;const d=clientData().slice().sort((a,b)=>a.name.localeCompare(b.name));s.innerHTML='<option value="">Select a client...</option>'+d.map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join("");if(selectedId)s.value=String(selectedId)}
async function refreshDatabaseSessionClientPicker(selectedId){const s=document.getElementById("sessionClientPicker"),t=coachToken();if(!s||!t)return;try{const r=await fetch(API_BASE+"/coach/clients",{headers:{Authorization:"Bearer "+t}});if(!r.ok)return;const d=await r.json();s.innerHTML='<option value="">Select a client...</option>'+d.map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join("");if(selectedId)s.value=String(selectedId)}catch(e){console.error("Could not load client picker",e)}}
function openSessionComposer(id){refreshSessionClientPicker(id);const p=document.getElementById("sessionComposer");if(p)p.style.display="block";const date=document.getElementById("sessionDate");if(date&&!date.value)date.value=new Date().toISOString().slice(0,10);document.getElementById("sessionTranscript")?.focus()}
function openSessionCalendar(){const d=document.getElementById("sessionDate");if(!d)return;try{if(d.showPicker)d.showPicker();else d.focus()}catch(e){d.focus()}}
function closeSessionComposer(){const p=document.getElementById("sessionComposer");if(p)p.style.display="none"}
function addSession(id){openSessionComposer(id)}
function saveSessionComposer(){const id=Number(document.getElementById("sessionClientPicker").value),raw=document.getElementById("sessionTranscript").value.trim(),date=document.getElementById("sessionDate").value;if(!id)return alert("Select a client.");if(!raw)return alert("Paste or type the session transcript or notes.");const d=clientData(),c=d.find(x=>x.id===id);if(!c)return alert("Client not found.");const lines=raw.split(/\n+/).map(x=>x.trim()).filter(Boolean);const issues=lines.filter(x=>/pain|sore|hurt|ache|limit|discomfort/i.test(x)).join(" ")||"None specifically recorded";const next=lines.filter(x=>/next|follow|plan|increase|decrease|focus/i.test(x)).join(" ")||"Review today’s notes and set the next progression.";const summary=lines.slice(0,4).join(" ")||raw;c.sessions.unshift({date:date||new Date().toISOString().slice(0,10),exercises:summary,response:"Session transcript captured and ready for Elise review.",issues,next,rawNotes:raw,approved:false});saveClients(d);document.getElementById("sessionTranscript").value="";closeSessionComposer();alert("Session saved to "+c.name+". It is marked for Elise review before client visibility.")}
function deleteClient(id){if(!confirm("Delete this client and session history?"))return;saveClients(clientData().filter(x=>x.id!==id))}
async function renderClients(){const el=document.getElementById("clientList");if(!el)return;const token=sessionStorage.getItem("fitcoach_coach_token");if(token){try{const r=await fetch(API_BASE+"/coach/clients",{headers:{Authorization:"Bearer "+token}});if(r.ok){const d=await r.json();el.innerHTML=d.length?d.map(c=>'<div class="client-card"><div class="client-head"><div><h3>'+esc(c.name)+'</h3><span class="badge">'+esc(c.goal||"Goal not entered")+'</span></div><div><button onclick="addSession('+c.id+')">+ Log Session</button></div></div><p><b>'+esc(c.email)+'</b></p><p>'+esc(c.notes||"No background notes yet.")+'</p><h4>Session History ('+c.sessions.length+')</h4>'+(c.sessions.length?c.sessions.map(s=>'<div class="session"><b>'+esc(s.date?new Date(s.date).toLocaleDateString():"")+'</b><p>'+esc(s.summary||s.rawNotes||"Session saved.")+'</p></div>').join(""):'<p class="muted">No sessions logged yet.</p>')+'</div>').join(""):'<p class="muted">No clients yet. Add the first client above.</p>';return}}catch(e){console.error("Could not load database clients",e)}}const d=clientData();el.innerHTML=d.length?'<p class="muted"><b>Local prototype records</b> — sign in as coach to view real client accounts.</p>'+d.map(c=>'<div class="client-card"><h3>'+esc(c.name)+'</h3><span class="badge">'+esc(c.goal||"Goal not entered")+'</span></div>').join(""):'<p class="muted">Sign in as coach to load real clients.</p>'}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
document.addEventListener("DOMContentLoaded",()=>{renderClients();refreshSessionClientPicker()});

const GOOGLE_REVIEW_URL="";
function feedbackData(){return JSON.parse(localStorage.getItem("fitcoach_feedback")||"[]")}
function saveFeedback(d){localStorage.setItem("fitcoach_feedback",JSON.stringify(d));renderFeedback()}
function submitFeedback(){const text=document.getElementById("feedbackText").value.trim();if(!text)return alert("Please add your feedback first.");const d=feedbackData();d.unshift({id:Date.now(),name:document.getElementById("feedbackName").value.trim()||"Anonymous client",text,consent:document.getElementById("feedbackConsent").checked,date:new Date().toLocaleDateString()});saveFeedback(d);document.getElementById("feedbackName").value="";document.getElementById("feedbackText").value="";document.getElementById("feedbackConsent").checked=false;document.getElementById("feedbackThanks").innerHTML="<b>Thank you.</b> Your feedback was saved for Elise."}
function openGoogleReview(){if(!GOOGLE_REVIEW_URL)return alert("Google Review test passed. The button works; Elise’s real Google Business review URL still needs to be connected before it can open the review page.");window.open(GOOGLE_REVIEW_URL,"_blank","noopener")}
function renderFeedback(){const el=document.getElementById("feedbackList");if(!el)return;const d=feedbackData();el.innerHTML=d.length?d.map(f=>'<div class="session"><div class="client-head"><b>'+esc(f.name)+'</b><span class="badge">'+(f.consent?"TESTIMONIAL OK":"PRIVATE FEEDBACK")+'</span></div><p>“'+esc(f.text)+'”</p><p class="muted">'+esc(f.date)+'</p></div>').join(""):'<p class="muted">No client feedback yet.</p>';const b=document.getElementById("googleReviewBtn");if(b&&!GOOGLE_REVIEW_URL){b.disabled=false;b.title="Test mode: verifies the button flow without opening a real review page."}}
document.addEventListener("DOMContentLoaded",renderFeedback);


const portalViews={
home:`<div class="grid"><div class="card wide"><p class="muted">YOUR NEXT STEP</p><h2>Ready for your next session?</h2><p>Elise has your plan ready. Your job is simple: show up, train, and keep building momentum.</p><button onclick="portalTab('workout')">Open My Next Workout</button></div><div class="card"><p class="muted">FROM ELISE</p><h3>Focus for next time</h3><p>Controlled reps, confident hinge position, and strong finishes.</p><button class="secondary" onclick="portalTab('recap')">Review Last Session</button></div></div>`,
workout:`<div class="grid"><div class="card wide"><p class="muted">NEXT WORKOUT</p><h2>Full Body Strength • Session 13</h2><p>Elise manages the details. Check movements off as you complete them.</p><div class="workout-checks"><label><input type="checkbox"> Goblet Squat <b>3 × 10</b></label><label><input type="checkbox"> DB Romanian Deadlift <b>3 × 10</b></label><label><input type="checkbox"> Incline Push-up <b>3 × 8</b></label><label><input type="checkbox"> Seated Cable Row <b>3 × 12</b></label></div></div><div class="card"><p class="muted">TODAY'S CUE</p><h3>Quality over quantity.</h3><p>Move with control and leave two strong reps in reserve.</p></div></div>`,
recap:`<div class="grid"><div class="card wide"><p class="muted">SESSION 12 • APPROVED BY ELISE</p><h2>Here’s what we did.</h2><p><b>Work:</b> Goblet squat, RDL, incline push-up and cable row.</p><p><b>Your wins:</b> Better squat depth, steadier tempo, and improved hinge control.</p><p><b>Elise’s note:</b> Keep the dumbbells close on the RDL and finish tall.</p><p><b>What’s next:</b> Small load increase if warm-up reps feel crisp.</p></div><div class="card"><h3>How did it feel?</h3><div class="feel-row"><button onclick="portalFeel(this)">Easy</button><button onclick="portalFeel(this)">Just Right</button><button onclick="portalFeel(this)">Tough</button></div><textarea class="answer" placeholder="Anything Elise should know?"></textarea></div></div>`,
progress:`<div class="grid"><div class="card wide"><p class="muted">YOUR PROGRESS</p><h2>Momentum you can see.</h2><div class="progress-bars"><p>Workout consistency <span>80%</span></p><div class="bar"><div class="fill" style="width:80%"></div></div><p>Strength goal <span>68%</span></p><div class="bar"><div class="fill" style="width:68%"></div></div><p>Movement confidence <span>75%</span></p><div class="bar"><div class="fill" style="width:75%"></div></div></div></div><div class="card"><h3>Recent wins</h3><p>✓ 4 sessions this month</p><p>✓ New goblet squat best</p><p>✓ Improved hinge control</p></div></div>`,
videos:`<div class="grid"><div class="card wide"><p class="muted">YOUR COACHING CLIPS</p><h2>See the cue. Remember the feeling.</h2><div class="video-placeholder"><b>RDL FORM CHECK</b><span>Elise: Keep the weights close and finish tall.</span></div></div><div class="card"><h3>Private video library</h3><p>Approved clips from your sessions will appear here once secure media storage is connected.</p></div></div>`,
ai:`<div class="grid"><div class="card wide ai-card"><p class="muted">ELISE AI COACH • SESSION MEMORY</p><h2>Ask about your training.</h2><p>Try: “What were my top 5 takeaways today?” or “What did Elise say about my RDL?”</p><div class="quick-prompts"><button onclick="askEliseAI('top')">Top 5 things from today</button><button onclick="askEliseAI('form')">What did Elise say about my form?</button><button onclick="askEliseAI('next')">What should I focus on next?</button></div><textarea id="aiQuestion" class="answer" placeholder="Ask Elise AI about an approved session..."></textarea><button onclick="askEliseAI('custom')">Ask Elise AI</button><div id="aiAnswer" class="ai-answer">Answers in this prototype come only from the approved sample session recap above.</div></div><div class="card"><h3>Trusted session memory</h3><p>Elise reviews the transcript first. Only approved coaching notes become client-facing AI context.</p></div></div>`,
message:`<div class="grid"><div class="card wide"><p class="muted">CHECK IN WITH ELISE</p><h2>One place for the things she should know.</h2><textarea id="portalMessage" class="answer" placeholder="A win, soreness, question, schedule note, or anything Elise should know before your next session..."></textarea><button onclick="portalMessage()">Save Check-in</button><p id="portalMessageStatus"></p></div><div class="card"><h3>Keep it simple.</h3><p>Elise owns the detailed training record. You only add what helps her coach your next session.</p></div></div>`,
capture:`<div class="grid"><div class="card wide"><p class="muted">ELISE • SESSION CAPTURE</p><h2>Turn a conversation into a useful recap.</h2><div class="capture-status"><span class="record-dot"></span><b>Recording not connected</b></div><p>With client consent, a future secure recorder can capture portions of the session. For this prototype, paste or type notes below to see the review workflow.</p><textarea id="sessionTranscript" class="answer tall" placeholder="Example: Joe’s goblet squat depth improved today. Used 35 lb for 3 sets of 10. On RDL, cue was keep dumbbells close and finish tall..."></textarea><button onclick="buildSessionDraft()">Create Draft From Notes</button><div id="sessionDraft"></div></div><div class="card"><h3>Approval gate</h3><p>Nothing from a raw transcript should become client-facing until Elise reviews and approves the summary.</p><p><b>Flow:</b><br>Consent → Capture → Transcript → Draft → Elise Review → Approve → Client Recap + AI</p></div></div>`
};
function portalTab(name){document.querySelectorAll("[data-portal]").forEach(b=>b.classList.toggle("active",b.dataset.portal===name));const el=document.getElementById("portalContent");if(el)el.innerHTML=portalViews[name]||portalViews.home}
function completeOnboarding(){const n=document.getElementById("onboardName").value.trim();if(!n){alert("Add your name to continue.");return}const goal=document.getElementById("onboardGoal").value;localStorage.setItem("fitcoach_portal_profile",JSON.stringify({name:n,goal:goal,schedule:document.getElementById("onboardSchedule").value,notes:document.getElementById("onboardNotes").value,recordConsent:document.getElementById("recordConsent").checked}));openPortal(n,goal)}
function demoPortal(){openPortal("Joe","Build strength")}
function openPortal(n,g){document.body.classList.add("client-mode");document.getElementById("portalWelcome").style.display="none";document.getElementById("portalDashboard").style.display="block";document.getElementById("portalGreeting").textContent="Good morning, "+n+".";document.getElementById("portalGoalLine").textContent="Goal: "+g+". Here’s what matters for your next session.";portalTab("home")}
function exitClientPortal(){document.body.classList.remove("client-mode");document.getElementById("portalDashboard").style.display="none";document.getElementById("portalWelcome").style.display="block";show("today")}
function portalFeel(btn){btn.parentElement.querySelectorAll("button").forEach(b=>b.classList.remove("selected"));btn.classList.add("selected")}
function portalMessage(){const e=document.getElementById("portalMessage"),st=document.getElementById("portalMessageStatus");if(!e.value.trim()){st.textContent="Add a check-in first.";return}st.innerHTML="<b>Check-in saved on this device.</b> Secure sync will replace local demo storage when client accounts are connected.";localStorage.setItem("fitcoach_portal_checkin",e.value.trim())}
function askEliseAI(type){const q=document.getElementById("aiQuestion"),out=document.getElementById("aiAnswer");let ans="";if(type==="top")ans="<b>Your top 5:</b> 1) Better squat depth. 2) Steadier tempo. 3) Improved RDL hinge control. 4) Keep the dumbbells close on RDLs. 5) If warm-ups feel crisp, Elise plans a small load increase.";else if(type==="form")ans="<b>Elise’s approved form note:</b> Your squat depth and tempo improved. On RDLs, keep the dumbbells close and finish tall.";else if(type==="next")ans="<b>Next focus:</b> controlled reps, confident hinge position, and a possible small load increase after warm-up.";else {const v=q.value.trim().toLowerCase();ans=!v?"Ask a question first.":v.includes("weight")?"The approved sample session does not include a confirmed weight, so I won’t guess.":v.includes("rdl")||v.includes("form")?"Elise’s approved note says to keep the dumbbells close on the RDL and finish tall.":"For this prototype I can answer from the approved sample recap only. Try asking about your squat, RDL, today’s wins, or next-session focus."}out.innerHTML=ans}
function buildSessionDraft(){const t=document.getElementById("sessionTranscript").value.trim(),d=document.getElementById("sessionDraft");if(!t){d.innerHTML="<p>Add session notes first.</p>";return}d.innerHTML='<div class="draft-review"><p class="muted">AI-ASSISTED DRAFT • NOT CLIENT VISIBLE</p><h3>Review before approval</h3><p><b>Source notes:</b> '+escapeHtml(t)+'</p><p><b>Suggested structure:</b> Exercises performed • coaching cues • client wins • issues/limitations • next-session plan.</p><button onclick="approveSessionDraft()">Approve Demo Recap</button></div>'}
function approveSessionDraft(){document.getElementById("sessionDraft").innerHTML='<div class="draft-review approved"><h3>✓ Approved for client recap</h3><p>This demonstrates the approval gate. In production, the approved structured record will be saved to the client database and become available to Elise AI Coach.</p></div>'}
function escapeHtml(v){return v.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
document.addEventListener("DOMContentLoaded",()=>{document.body.classList.remove("client-mode");});

const API_BASE="https://fit-coach-os-api.onrender.com";
function coachToken(){return sessionStorage.getItem("fitcoach_coach_token")||""}
async function coachLogin(){const e=document.getElementById("coachEmail").value.trim(),p=document.getElementById("coachPassword").value,st=document.getElementById("coachLoginStatus");if(!e||!p){st.textContent="Enter your coach email and password.";return}st.textContent="Signing in...";try{const r=await fetch(API_BASE+"/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:e,password:p})});const d=await r.json();if(!r.ok||d.role!=="coach")throw new Error(d.error||"Coach login failed");sessionStorage.setItem("fitcoach_coach_token",d.token);st.innerHTML="<b>Signed in as "+escapeHtml(d.name)+".</b>";document.getElementById("coachLogin").style.display="none";document.getElementById("inviteForm").style.display="block";renderClients();refreshDatabaseSessionClientPicker()}catch(x){st.textContent=x.message}}
async function createClientInvite(){const n=document.getElementById("inviteName").value.trim(),e=document.getElementById("inviteEmail").value.trim(),st=document.getElementById("inviteStatus");if(!n||!e||!e.includes("@")){st.textContent="Add the client’s name and a valid email address.";return}const t=coachToken();if(!t){st.textContent="Coach sign in required.";document.getElementById("coachLogin").style.display="block";document.getElementById("inviteForm").style.display="none";return}st.textContent="Sending secure invitation...";try{const r=await fetch(API_BASE+"/coach/invites",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+t},body:JSON.stringify({name:n,email:e})});const d=await r.json();if(r.status===401){sessionStorage.removeItem("fitcoach_coach_token");document.getElementById("coachLogin").style.display="block";document.getElementById("inviteForm").style.display="none";throw new Error("Coach session expired. Sign in again.")}if(!r.ok)throw new Error(d.error||"Could not send invitation");if(d.testInviteUrl){st.innerHTML="<b>Test invitation created.</b> Resend cannot email this address in test mode.<br><a class=\"test-invite-link\" href=\""+d.testInviteUrl+"\">Open Secure Test Invitation</a>"}else{st.innerHTML="<b>Invitation sent to "+escapeHtml(e)+".</b> The secure link expires in 48 hours."}document.getElementById("inviteName").value="";document.getElementById("inviteEmail").value=""}catch(x){st.textContent=x.message}}
function testInvitedClient(){const raw=localStorage.getItem("fitcoach_test_invite");if(!raw){alert("Create a test invitation first.");return}const x=JSON.parse(raw);show("portal");document.getElementById("portalWelcome").style.display="block";document.getElementById("portalDashboard").style.display="none";document.getElementById("onboardName").value=x.name;document.getElementById("onboardName").readOnly=true;window.scrollTo({top:0,behavior:"smooth"})}
function resetTestClient(){localStorage.removeItem("fitcoach_test_invite");localStorage.removeItem("fitcoach_portal_profile");localStorage.removeItem("fitcoach_portal_checkin");const st=document.getElementById("inviteStatus");if(st)st.innerHTML="<b>Test client reset.</b> You can create a fresh invitation now.";const ac=document.getElementById("inviteActions");if(ac)ac.style.display="none"}


document.addEventListener("DOMContentLoaded",()=>{const logged=!!coachToken(),l=document.getElementById("coachLogin"),f=document.getElementById("inviteForm");if(l)l.style.display=logged?"none":"block";if(f)f.style.display=logged?"block":"none"});

async function acceptSecureInvite(){
 const token=new URLSearchParams(location.search).get("invite"),st=document.getElementById("acceptInviteStatus"),p=document.getElementById("invitePassword").value;
 if(!token){st.textContent="Invitation link is missing.";return}
 if(!p||p.length<8){st.textContent="Choose a password with at least 8 characters.";return}
 st.textContent="Creating your private account...";
 try{
  const r=await fetch(API_BASE+"/auth/accept-invite",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,password:p,goal:document.getElementById("onboardGoal").value,schedule:document.getElementById("onboardSchedule").value,notes:document.getElementById("onboardNotes").value,recordConsent:document.getElementById("recordConsent").checked})});
  const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not create account");
  localStorage.setItem("fitcoach_portal_profile",JSON.stringify({name:document.getElementById("onboardName").value||"Client",goal:document.getElementById("onboardGoal").value,experience:document.getElementById("onboardExperience").value,schedule:document.getElementById("onboardSchedule").value,notes:document.getElementById("onboardNotes").value}));
  history.replaceState({},document.title,location.pathname);openPortal(document.getElementById("onboardName").value||"Client",document.getElementById("onboardGoal").value)
 }catch(x){st.textContent=x.message}
}
document.addEventListener("DOMContentLoaded",()=>{
 const token=new URLSearchParams(location.search).get("invite");
 if(token){
  show("portal");
  const s=document.getElementById("secureInviteSetup");if(s)s.style.display="block";
  const b=document.getElementById("portalEnterButton");if(b){b.textContent="Create My Account & Enter Portal";b.onclick=secureInviteSubmit}
  const demo=[...document.querySelectorAll("#portalWelcome button.secondary")];demo.forEach(x=>x.style.display="none");
  const note=document.querySelector("#portalWelcome .test-note");if(note)note.style.display="none";
  window.scrollTo({top:0});
 }
});

function activateSecureInviteView(){
 const token=new URLSearchParams(location.search).get("invite"); if(!token)return;
 document.body.classList.add("client-invite-mode");
 ["coachHero","coachSportStrip","coachTabs"].forEach(id=>{const el=document.getElementById(id);if(el)el.style.display="none"});
 document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));
 const portal=document.getElementById("portal");if(portal)portal.classList.add("active");
 const welcome=document.getElementById("portalWelcome");if(welcome)welcome.style.display="block";
 const dash=document.getElementById("portalDashboard");if(dash)dash.style.display="none";
 const secure=document.getElementById("secureInviteSetup");if(secure)secure.style.display="block";
 const btn=document.getElementById("portalEnterButton");if(btn){btn.textContent="Create My Account & Enter Portal";btn.onclick=acceptSecureInvite}
 document.querySelectorAll("#portalWelcome button.secondary").forEach(x=>x.style.display="none");
 const note=document.querySelector("#portalWelcome .test-note");if(note)note.style.display="none";
 const name=document.getElementById("onboardName");if(name&&name.value==="Joe")name.value="";
 window.scrollTo({top:0});
}

document.addEventListener("DOMContentLoaded",activateSecureInviteView);

function secureInviteSubmit(e){
 if(e){e.preventDefault();e.stopPropagation()}
 const token=new URLSearchParams(location.search).get("invite");
 if(token){acceptSecureInvite();return false}
 completeOnboarding();return false
}
